# Generated by Django 3.2.8 on 2021-11-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('family', 'family'), ('friends', 'friends'), ('self', 'self'), ('lovers', 'lovers'), ('senior/junior', 'senior/junior')], default='self', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mad.restaurant')),
            ],
        ),
    ]
