# Generated by Django 3.2.8 on 2021-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='choice',
            field=models.CharField(choices=[('family', 'family'), ('friends', 'friends'), ('self', 'self'), ('lovers', 'lovers'), ('senior/junior', 'senior/junior')], default='self', max_length=20),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
