# Generated by Django 3.2.8 on 2021-11-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad', '0005_auto_20211119_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='019plate1_114171.png', upload_to='images/'),
        ),
    ]
