# Generated by Django 3.2.8 on 2021-11-19 13:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mad', '0007_auto_20211119_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
