# Generated by Django 3.2.8 on 2021-11-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad', '0009_auto_20211120_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='choice',
            field=models.CharField(choices=[('family', 'family'), ('friends', 'friends'), ('self', 'self'), ('lovers', 'lovers'), ('senior', 'senior')], default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='images/019plate1_114171.png', upload_to='images/'),
        ),
    ]
